"""Generate static discovery guidance from the CLI's single source of truth."""

import argparse
from pathlib import Path

from reflex_axi.catalog import DESCRIPTION, GUIDANCE, SKILL_GUIDE

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
target = Path("skills/reflex-axi/SKILL.md")
commands = "\n".join(
    "- `uvx --from git+https://github.com/rocitsoftwaresolutions/reflex-axi " + line + "`"
    for line in GUIDANCE
)
content = f"""---
name: reflex-axi
description: Use for bounded fuzzy judgment, routing, filtering, scoring, batch evaluation, and evidence-gated improvement before expensive reasoning.
---

<!-- Generated by scripts/generate_skill.py; do not edit manually. -->

{DESCRIPTION}

{commands}

{SKILL_GUIDE.strip()}
"""
if args.check:
    if not target.exists() or target.read_text() != content:
        raise SystemExit("Discovery skill is stale; run scripts/generate_skill.py")
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
